// <auto-generated />
using System;
using Akalaat.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akalaat.DAL.Data.Migrations
{
    [DbContext(typeof(AkalaatDbContext))]
    [Migration("20240307213350_Intialdatabase")]
    partial class Intialdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akalaat.DAL.Models.Address_Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Region_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Region_ID");

                    b.ToTable("Address_Book");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Available_Delivery_Area", b =>
                {
                    b.Property<int>("Branch_ID")
                        .HasColumnType("int");

                    b.Property<int>("Region_ID")
                        .HasColumnType("int");

                    b.HasKey("Branch_ID", "Region_ID");

                    b.HasIndex("Region_ID");

                    b.ToTable("AvailableDeliveryAreas");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Branch", b =>
                {
                    b.Property<int>("Branch_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Branch_ID"));

                    b.Property<DateTime>("Close_Hour")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estimated_Delivery_Time")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDineIn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Open_Hour")
                        .HasColumnType("datetime2");

                    b.Property<int>("Region_ID")
                        .HasColumnType("int");

                    b.Property<int>("Resturant_ID")
                        .HasColumnType("int");

                    b.HasKey("Branch_ID");

                    b.HasIndex("Region_ID");

                    b.HasIndex("Resturant_ID");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Branch_Reservation", b =>
                {
                    b.Property<int>("Branch_ID")
                        .HasColumnType("int");

                    b.Property<int>("Reservation_ID")
                        .HasColumnType("int");

                    b.HasKey("Branch_ID", "Reservation_ID");

                    b.HasIndex("Reservation_ID");

                    b.ToTable("Branch_Reservation");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Menu_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Menu_ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Dish", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Dish_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.District", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("City_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("City_ID");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Extra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Extra");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Item", b =>
                {
                    b.Property<int>("Item_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOffer")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int?>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Item_ID");

                    b.HasIndex("MenuID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Item_Size", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Item_Size");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Items_in_Offer", b =>
                {
                    b.Property<int>("Offer_ID")
                        .HasColumnType("int");

                    b.Property<int>("Item_ID")
                        .HasColumnType("int");

                    b.HasKey("Offer_ID", "Item_ID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Items_in_Offer");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Resturant_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Menu_Item_Size", b =>
                {
                    b.Property<int>("Item_ID")
                        .HasColumnType("int");

                    b.Property<int>("Item_Size_ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size_Image_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Item_ID", "Item_Size_ID");

                    b.HasIndex("Item_Size_ID");

                    b.ToTable("Menu_Item_Size");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Mood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mood");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Offer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menu_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offer_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Menu_ID");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Arrival_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("District_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("District_ID");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Reservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("End_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Customer_ID");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cover_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Menu_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Vendor_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Menu_ID")
                        .IsUnique()
                        .HasFilter("[Menu_ID] IS NOT NULL");

                    b.HasIndex("Vendor_ID");

                    b.ToTable("Resturant");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant_Dish", b =>
                {
                    b.Property<int>("Resturant_ID")
                        .HasColumnType("int");

                    b.Property<int>("Dish_ID")
                        .HasColumnType("int");

                    b.HasKey("Resturant_ID", "Dish_ID");

                    b.HasIndex("Dish_ID");

                    b.ToTable("Resturant_Dish");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant_Mood", b =>
                {
                    b.Property<int>("Resturant_ID")
                        .HasColumnType("int");

                    b.Property<int>("Mood_ID")
                        .HasColumnType("int");

                    b.HasKey("Resturant_ID", "Mood_ID");

                    b.HasIndex("Mood_ID");

                    b.ToTable("Resturant_Mood");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("No_of_Likes")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("Resturant_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Resturant_ID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Admin", b =>
                {
                    b.HasBaseType("Akalaat.DAL.Models.ApplicationUser");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Customer", b =>
                {
                    b.HasBaseType("Akalaat.DAL.Models.ApplicationUser");

                    b.Property<int?>("Address_Book_ID")
                        .HasColumnType("int");

                    b.HasIndex("Address_Book_ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Vendor", b =>
                {
                    b.HasBaseType("Akalaat.DAL.Models.ApplicationUser");

                    b.Property<int?>("Resturant_ID")
                        .HasColumnType("int");

                    b.HasIndex("Resturant_ID");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Address_Book", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Region", "Region")
                        .WithMany("address_Books")
                        .HasForeignKey("Region_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Available_Delivery_Area", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Branch", "Branch")
                        .WithMany("delivery_Areas")
                        .HasForeignKey("Branch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Region", "Region")
                        .WithMany("delivery_Areas")
                        .HasForeignKey("Region_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Branch", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Region", "Region")
                        .WithMany("branches")
                        .HasForeignKey("Region_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Resturant", "Resturant")
                        .WithMany("branches")
                        .HasForeignKey("Resturant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Resturant");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Branch_Reservation", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Branch", "Branch")
                        .WithMany("branch_Reservations")
                        .HasForeignKey("Branch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Reservation", "Reservation")
                        .WithMany("branch_Reservations")
                        .HasForeignKey("Reservation_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Category", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Menu", "Menu")
                        .WithMany("categories")
                        .HasForeignKey("Menu_ID");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.District", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.City", "City")
                        .WithMany("districts")
                        .HasForeignKey("City_ID");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Extra", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Item", "Item")
                        .WithMany("extras")
                        .HasForeignKey("Item_ID");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Item", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Menu", null)
                        .WithMany("items")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Items_in_Offer", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Item", "Item")
                        .WithMany("items_In_Offers")
                        .HasForeignKey("Item_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Offer", "Offer")
                        .WithMany("items_In_Offers")
                        .HasForeignKey("Offer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Menu_Item_Size", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Item", "Item")
                        .WithMany("menu_Item_Sizes")
                        .HasForeignKey("Item_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Item_Size", "Item_Size")
                        .WithMany("menu_Item_Sizes")
                        .HasForeignKey("Item_Size_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Item_Size");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Offer", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Menu", "Menu")
                        .WithMany("offers")
                        .HasForeignKey("Menu_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Order", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Customer", "Customer")
                        .WithMany("orders")
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Region", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.District", "District")
                        .WithMany("regions")
                        .HasForeignKey("District_ID");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Reservation", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Customer", "Customer")
                        .WithMany("reservations")
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Menu", "Menu")
                        .WithOne("Resturant")
                        .HasForeignKey("Akalaat.DAL.Models.Resturant", "Menu_ID");

                    b.HasOne("Akalaat.DAL.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("Vendor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant_Dish", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Dish", "Dish")
                        .WithMany("resturant_Dishes")
                        .HasForeignKey("Dish_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Resturant", "Resturant")
                        .WithMany("resturant_Dishes")
                        .HasForeignKey("Resturant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Resturant");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant_Mood", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Mood", "Mood")
                        .WithMany("resturant_Moods")
                        .HasForeignKey("Mood_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Resturant", "Resturant")
                        .WithMany("resturant_Moods")
                        .HasForeignKey("Resturant_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("Resturant");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Review", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Customer", "Customer")
                        .WithMany("reviews")
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Resturant", "Resturant")
                        .WithMany("reviews")
                        .HasForeignKey("Resturant_ID");

                    b.Navigation("Customer");

                    b.Navigation("Resturant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Admin", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Akalaat.DAL.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Customer", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.Address_Book", "Address_Book")
                        .WithMany()
                        .HasForeignKey("Address_Book_ID");

                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Akalaat.DAL.Models.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address_Book");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Vendor", b =>
                {
                    b.HasOne("Akalaat.DAL.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Akalaat.DAL.Models.Vendor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akalaat.DAL.Models.Resturant", "Resturant")
                        .WithMany()
                        .HasForeignKey("Resturant_ID");

                    b.Navigation("Resturant");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Branch", b =>
                {
                    b.Navigation("branch_Reservations");

                    b.Navigation("delivery_Areas");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.City", b =>
                {
                    b.Navigation("districts");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Dish", b =>
                {
                    b.Navigation("resturant_Dishes");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.District", b =>
                {
                    b.Navigation("regions");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Item", b =>
                {
                    b.Navigation("extras");

                    b.Navigation("items_In_Offers");

                    b.Navigation("menu_Item_Sizes");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Item_Size", b =>
                {
                    b.Navigation("menu_Item_Sizes");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Menu", b =>
                {
                    b.Navigation("Resturant")
                        .IsRequired();

                    b.Navigation("categories");

                    b.Navigation("items");

                    b.Navigation("offers");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Mood", b =>
                {
                    b.Navigation("resturant_Moods");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Offer", b =>
                {
                    b.Navigation("items_In_Offers");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Region", b =>
                {
                    b.Navigation("address_Books");

                    b.Navigation("branches");

                    b.Navigation("delivery_Areas");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Reservation", b =>
                {
                    b.Navigation("branch_Reservations");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Resturant", b =>
                {
                    b.Navigation("branches");

                    b.Navigation("resturant_Dishes");

                    b.Navigation("resturant_Moods");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Akalaat.DAL.Models.Customer", b =>
                {
                    b.Navigation("orders");

                    b.Navigation("reservations");

                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
